#%RAML 1.0 DataType

type: string
description: |
  RData is the actual data associated with a record.
examples:
  A: "1.2.3.4"
  AAAA: "2606:2800:220:1:248:1893:25c8:1946"
  CNAME: "foo.example.com"
  TXT: "This is a single TXT record"
  MX: "1 mail.example.com."
