#%RAML 1.0 DataType

# File: types/ttl.raml
# Thile data type represents a DNS Time To Live

type: integer
description: |
  TTL (Time To Live) is the number in seconds that a DNS record should be cached.
minimum: 0
maximum: 2147483647
