#%RAML 1.0 Library

Error: !include error.raml
Errors: !include errors.raml
Auth: !include auth.raml
UUID: !include uuid.raml
Record: !include record.raml
TTL: !include ttl.raml
RData: !include rdata.raml
RRSet: !include rrset.raml
SysID: !include ../parameters/sys_id.raml
EMSAddress: !include ../parameters/ems_address.raml
NetconfIP: !include ../parameters/netconf_ip.raml
NetconfPort: !include ../parameters/netconf_port.raml
ExtConnectionPoints: !include ../parameters/ext_connection_points.raml
IntConnectionPoints: !include ../parameters/int_connection_points.raml
Status: !include ../parameters/status.raml
Timeout: !include ../parameters/timeout.raml
VNFCID: !include ../parameters/vnfc_id.raml
VNFCIDS: !include ../parameters/vnfc_ids.raml
Identity: !include identity.raml
Operation: !include operation.raml
ConfigParameters: !include config_parameters.raml
StopRestartParameters: !include stop_restart_parameters.raml
Mode: !include mode.raml
VNFC: !include vnfc.raml
