#%RAML 1.0 Trait

# File: traits/4xx.raml

responses:
  400:
    description: "Bad Request"
    body:
      application/json:
        type: object
        example:
          {
            "description": "Malformed request, content must be application/json encoded",
            "error": "Bad Request",
            "status_code": 400
          }

  401:
    description: "Unauthorized"
    body:
      application/json:
        type: object
        example:
          {
            "description": "Request does not contain an access token",
            "error": "Authorization Required",
            "status_code": 401
          }
