#%RAML 1.0 Trait

queryParameters:
  netconf_ip?:
    type: string
    description: |
      `netconf_ip` is qulified as a unique query parameter for filtering.

      The use of `'&'` (logical AND) and `'|'` (logical OR) may be used to create a compound boolean expression for filtering.
    example: "10.1.2.42"
