#%RAML 1.0 Trait

queryParameters:
  sys_id?:
    type: UUID
    description: |
      `sys_id` is qulified as a unique query parameter for filtering.

      The use of `'&'` (logical AND) and `'|'` (logical OR) may be used to create a compound boolean expression for filtering.
    example: 123e4567-e89b-12d3-a456-426655440000
