#%RAML 1.0 Library

2xx: !include /traits/2xx.raml
4xx: !include /traits/4xx.raml
filterable: !include /traits/filterable.raml
sortable: !include /traits/sortable.raml
limitable: !include /traits/limitable.raml
sys_id: !include /traits/sys_id.raml
